<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<TargetPlatformIdentifier>windows</TargetPlatformIdentifier>
		<TargetPlatformVersion>10.0.22000.0</TargetPlatformVersion>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>window</RootNamespace>
		<Nullable>enable</Nullable>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x64;win-x86;win-arm64</RuntimeIdentifiers>
		<UseRidGraph>true</UseRidGraph>
		<UseWinUI>true</UseWinUI>
		<WindowsPackageType>None</WindowsPackageType>
		<DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240802000" />
		<PackageReference Include="Vortice.Direct3D12" Version="3.5.0" />
		<PackageReference Include="Vortice.Dxc" Version="3.5.0" />
		<PackageReference Include="Vortice.WinUI" Version="3.5.0" />
		<PackageReference Include="WindowsTerminal.WinUI3.Control" Version="1.11.3471" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Triangle.hlsl">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Triangle.vs.blob">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>